name: Build and deploy app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer and Terraform dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip wget

      - name: Download and install Packer
        run: |
          if ! command -v packer &> /dev/null
          then
            wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
            unzip packer_1.7.4_linux_amd64.zip
            sudo mv packer /usr/local/bin/
          else
            echo "Packer is already installed"
          fi

      - name: Download and install Terraform
        run: |
          if ! command -v terraform &> /dev/null
          then
            wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
            unzip terraform_1.0.9_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
          else
            echo "Terraform is already installed"
          fi

      - name: Send confirmation email
        uses: actions/email@v1
        with:
          subject: 'Confirm deployment to tencent'
          body: |
            Are you sure you want to deploy to tencent?
            Type 'yes' to confirm or 'no' to cancel.
          to: ${{ github.event.sender.email }}

      - name: Deploy to AWS
        if: steps.confirm.outputs.body == 'yes'
        run: |
          echo "Has replied yes"

      - name: Build image
        run: packer version

      - name: Build image
        run: terraform version

#      - name: Build image
#        run: packer build myapp.json
#
#      - name: Initialize Terraform
#        run: terraform init
#
#      - name: Apply Terraform
#        run: terraform apply -auto-approve

