name: Build and deploy app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TENCENTCLOUD_REGION: ap-guangzhou
  TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
  TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer and Terraform dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip wget

      - name: Download and install Packer
        run: |
          if ! command -v packer &> /dev/null
          then
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install packer
            y | sudo mv packer /usr/local/bin/
          else
            echo "Packer is already installed"
          fi

      - name: Download and install Terraform
        run: |
          if ! command -v terraform &> /dev/null
          then
            wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
            unzip terraform_1.0.9_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
          else
            echo "Terraform is already installed"
          fi

      - name: Download and install Packer plugin
        run: packer plugins install github.com/hashicorp/tencentcloud

      - name: packer version
        run: packer version

      - name: terraform version
        run: terraform version

      - name: Build image
        run: |
          packer build packer/packer_tencentcloud_cvm_jenkins_1.0.json
#
#      - name: Initialize Terraform
#        run: terraform init
#
#      - name: Apply Terraform
#        run: terraform apply -auto-approve

