name: Test and Deploy

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to production
        run: npm run deploy -- --env=production

      - name: Send notification
        uses: appleboy/slack-action@master
        with:
          status: ${{ job.status }}
          text: "Event: ${{ github.event_name }}\nType: ${{ github.event.pull_request ? 'PR' : 'Release' }}\nNumber: ${{ github.event.pull_request?.number }}${{ github.event.release?.tag_name ? '' : (github.event.release?.name ? ' (' + github.event.release?.name + ')' : '') }}"

      - name: Use the version number
        run: echo "name- ${Type}, number- ${Number}"