name: Test and Deploy

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get PR number or Release version
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR number: ${{ github.event.number }}"
            echo "RELEASE_VERSION=${{ github.event.number }}"
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "RELEASE_VERSION=${{ github.event.release.tag_name }}"
          fi

      - name: Use the PR number or Release version
        run: echo "PR number or Release version ${RELEASE_VERSION}"