name: Test and Deploy

on:
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get PR number and Release version
          run: |
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "PR number: ${{ github.event.number }}"
            elif [ "${{ github.event_name }}" == "release" ]; then
              echo "Release version: ${{ github.event.release.tag_name }}"
            fi